#ifndef SLELASKU_GLOBAL_H
#define SLELASKU_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SLELASKU_LIBRARY)
#  define SLELASKUSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SLELASKUSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SLELASKU_GLOBAL_H
